# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  projectFile: SmartSftp/Cli.csproj

steps:
- checkout: self
  submodules: true

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: gitversion/setup@0
  inputs: 
    versionSpec: '5.x'

- script: echo $(GitVersion.NuGetVersionV2)

- task: gitversion/execute@0

- script: |
    dotnet pack $(ProjectFile) -p:PackageVersion=$(GitVersion.NuGetVersionV2) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget'